
exporter_port: 9158 # Port on which prometheu can call this exporter to get metrics
log_level: info
json_data_urls:
- url: http://cluster-status # Url to get json data used for fetching metric values
  label: kubernetes
metric_name_prefix: kubernetes # All metric names will be prefixed with this value
metrics:
- name: total_nodes # Final metric name will be cluster_total_nodes
  description: Total number of nodes in cluster
  path: $.total
- name: alive_nodes # Final metric name will be cluster_alive_nodes
  description: Number of live nodes in cluster
  path: count($.data[@.status is "alive"])
